services:
  backend:
    build: .
    image: nisark786/choconut-backend:latest
    container_name: choconut_backend
    command: >
      sh -c "
        echo 'Waiting for Redis...' &&
        while ! nc -z redis 6379; do sleep 0.1; done &&
        echo 'Redis started' &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput --clear &&
        daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles 
      - ./media:/app/media
    restart: always
    networks:
      - choconut_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  celery_worker:
    image: nisark786/choconut-backend:latest
    container_name: choconut_celery_worker
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - choconut_network  
    restart: always

  celery_beat:
    image: nisark786/choconut-backend:latest
    container_name: choconut_celery_beat
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - choconut_network  
    restart: always

  redis:
    image: redis:7-alpine
    container_name: choconut_redis
    ports:
      - "6379:6379"
    networks:
      - choconut_network  
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: choconut_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro 
      - static_volume:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - backend
    networks:
      - choconut_network
    restart: always

networks:
  choconut_network:
    driver: bridge

volumes:
  frontend_assets:
  static_volume: