name: Choconut Deploy

on:
  push:
    branches: [ main ] # Deploy whenever you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build & Push Backend
      - name: Build Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/choconut-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/choconut-backend:latest

      # Build & Push Frontend
      - name: Build Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/choconut-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/choconut-frontend:latest

      # Deploy to EC2
      - name: SSH and Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/choconut-project/backend
            docker-compose pull
            docker-compose up -d
            docker image prune -f # Essential to save space!
